---
name: 🔒️ Security

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      scan_docker:
        default: false
        description: docker check
        type: boolean
      scan_python:
        default: false
        description: python check
        type: boolean
      scan_iac:
        default: false
        description: iac check
        type: boolean
    secrets:
      SNYK_TOKEN:
        required: true

jobs:
  docker:
    if: ${{ inputs.scan_docker }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - run: docker build -t ${{ github.repository }}:${{ github.sha }} .
      - uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ github.repository }}:${{ github.sha }}
          args: --fail-on=all

  python:
    if: ${{ inputs.scan_python }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements.txt
      - uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  terraform:
    if: ${{ inputs.scan_iac }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
