---
name: 🔒️ Security

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      scan_docker:
        default: false
        description: docker check
        type: boolean
      scan_python:
        default: false
        description: python check
        type: boolean
      scan_iac:
        default: false
        description: iac check
        type: boolean
      use_codeql:
        default: false
        description: integrate with GitHub CodeQL
        type: boolean
    secrets:
      SNYK_TOKEN:
        required: true

jobs:
  docker:
    if: ${{ inputs.scan_docker }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - run: docker build -t ${{ github.repository }}:${{ github.sha }} .
      - uses: snyk/actions/docker@master
        continue-on-error: ${{ inputs.use_codeql }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ github.repository }}:${{ github.sha }}
          args: --fail-on=all
      - uses: github/codeql-action/upload-sarif@v2
        if: ${{ inputs.use_codeql }}
        with:
          sarif_file: snyk.sarif

  python:
    if: ${{ inputs.scan_python }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements.txt
      - uses: snyk/actions/python@master
        continue-on-error: ${{ inputs.use_codeql }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - uses: github/codeql-action/upload-sarif@v2
        if: ${{ inputs.use_codeql }}
        with:
          sarif_file: snyk.sarif

  terraform:
    if: ${{ inputs.scan_iac }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snyk/actions/iac@master
        continue-on-error: ${{ inputs.use_codeql }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - uses: github/codeql-action/upload-sarif@v2
        if: ${{ inputs.use_codeql }}
        with:
          sarif_file: snyk.sarif
